# Generated by Django 4.2.4 on 2023-09-04 17:24

import django.core.files.storage
from django.db import migrations, models
import employees.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=128, verbose_name='Nombre(s)')),
                ('last_name', models.CharField(max_length=128, verbose_name='Apellidos')),
                ('type_blood', models.CharField(blank=True, choices=[('A +', 'A +'), ('A -', 'A -'), ('B +', 'B +'), ('B -', 'B -'), ('AB +', 'AB +'), ('AB -', 'AB -'), ('O +', 'O +'), ('O -', 'O -')], default='', max_length=4, verbose_name='Tipo de Sangre')),
                ('photo', models.ImageField(blank=True, default='C:\\Users\\iceda\\PycharmProjects\\conexiones\\weport-examentecnico\\src\\media//user-default.png', storage=django.core.files.storage.FileSystemStorage(location='C:\\Users\\iceda\\PycharmProjects\\conexiones\\weport-examentecnico\\src\\media/'), upload_to=employees.models.file_user_path, verbose_name='Foto del empleado')),
                ('qr_code_url', models.CharField(max_length=128)),
                ('qr_code', models.FileField(editable=False, storage=django.core.files.storage.FileSystemStorage(location='C:\\Users\\iceda\\PycharmProjects\\conexiones\\weport-examentecnico\\src\\media/'), upload_to=employees.models.file_user_path)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
