# Generated by Django 4.2.4 on 2023-09-04 17:46

import django.core.files.storage
from django.db import migrations, models
import employees.models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='is_active',
            field=models.BooleanField(default=True, editable=False),
        ),
        migrations.AlterField(
            model_name='employee',
            name='photo',
            field=models.ImageField(blank=True, default='C:\\Users\\iceda\\PycharmProjects\\conexiones\\weport-examentecnico\\src\\media//employee-default.png', storage=django.core.files.storage.FileSystemStorage(location='C:\\Users\\iceda\\PycharmProjects\\conexiones\\weport-examentecnico\\src\\media/'), upload_to=employees.models.file_user_path, verbose_name='Foto del empleado'),
        ),
    ]
