# Generated by Django 4.2.4 on 2023-09-05 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emergency_contacts', '0002_emergencycontact_priority'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emergencycontact',
            options={'ordering': ('priority',)},
        ),
        migrations.AlterField(
            model_name='emergencycontact',
            name='mobile',
            field=models.PositiveBigIntegerField(verbose_name='Celular'),
        ),
    ]
